version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chiranjiv-waitlist"
resolve_s3 = true
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
region = "ap-south-1"
parameter_overrides = "StageName=dev CorsOrigin=https://localhost:5173 DatabaseUrl="


